package Grafico;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import util.PosicaoFormulario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
 
/**
 *
 * @author bielh
 */
public class principal extends javax.swing.JFrame {

    PosicaoFormulario form = new PosicaoFormulario();
    
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        setExtendedState(principal.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jDesktop = new javax.swing.JDesktopPane();
        jmbBarraMenu = new javax.swing.JMenuBar();
        jmCadastramento = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itens = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmOrcamento = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmLaudo = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planilha Orcamento");
        setIconImages(null);
        setLocationByPlatform(true);
        setResizable(false);

        jDesktop.setBackground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jmbBarraMenu.setBackground(new java.awt.Color(242, 242, 242));

        jmCadastramento.setIcon(new javax.swing.ImageIcon("C:\\programacao\\java\\superchoque2000\\src\\main\\java\\img\\cadastro.png")); // NOI18N
        jmCadastramento.setMnemonic('c');
        jmCadastramento.setText("Cadastrmento ");
        jmCadastramento.setToolTipText("");
        jmCadastramento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastramentoActionPerformed(evt);
            }
        });
        jmCadastramento.add(jSeparator3);

        itens.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itens.setIcon(new javax.swing.ImageIcon("C:\\programacao\\java\\superchoque2000\\src\\main\\java\\img\\itens.png")); // NOI18N
        itens.setText("Itens");
        itens.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                itensComponentShown(evt);
            }
        });
        itens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itensActionPerformed(evt);
            }
        });
        jmCadastramento.add(itens);
        jmCadastramento.add(jSeparator4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\programacao\\java\\superchoque2000\\src\\main\\java\\img\\maodeobra.png")); // NOI18N
        jMenuItem1.setText("Mão de obra");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmCadastramento.add(jMenuItem1);
        jmCadastramento.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\programacao\\java\\superchoque2000\\src\\main\\java\\img\\outros.png")); // NOI18N
        jMenuItem2.setText("Diversos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmCadastramento.add(jMenuItem2);

        jmbBarraMenu.add(jmCadastramento);

        jmOrcamento.setIcon(new javax.swing.ImageIcon("C:\\programacao\\java\\superchoque2000\\src\\main\\java\\img\\orcamento.png")); // NOI18N
        jmOrcamento.setMnemonic('o');
        jmOrcamento.setText("Orcamento");
        jmOrcamento.setToolTipText("");
        jmOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOrcamentoActionPerformed(evt);
            }
        });
        jmOrcamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmOrcamentoKeyPressed(evt);
            }
        });

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\programacao\\java\\superchoque2000\\src\\main\\java\\img\\SPDA.png")); // NOI18N
        jMenuItem5.setText("SPDA");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmOrcamento.add(jMenuItem5);

        jmLaudo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmLaudo.setIcon(new javax.swing.ImageIcon("C:\\programacao\\java\\superchoque2000\\src\\main\\java\\img\\Laudo.png")); // NOI18N
        jmLaudo.setText("Laudo");
        jmLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLaudoActionPerformed(evt);
            }
        });
        jmOrcamento.add(jmLaudo);

        jmbBarraMenu.add(jmOrcamento);

        setJMenuBar(jmbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        setSize(new java.awt.Dimension(554, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itensActionPerformed
       SwingUtilities.invokeLater(() -> {
        ItensGrafico tela ;
        form.abrirFormulario(tela= new ItensGrafico() , jDesktop);
  
        });
    }//GEN-LAST:event_itensActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         SwingUtilities.invokeLater(() -> {
        OutrosGrafico tela ;
        form.abrirFormulario(tela= new OutrosGrafico() , jDesktop);
       });
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void itensComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_itensComponentShown
        // TODO add your handling code here:
       
    }//GEN-LAST:event_itensComponentShown

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      SwingUtilities.invokeLater(() -> {
        MaodeObraGrafico tela ;
        form.abrirFormulario(tela= new MaodeObraGrafico() , jDesktop);
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmCadastramentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastramentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastramentoActionPerformed

    private void jmOrcamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmOrcamentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmOrcamentoKeyPressed

    private void jmOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOrcamentoActionPerformed
        
    }//GEN-LAST:event_jmOrcamentoActionPerformed

    private void jmLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLaudoActionPerformed
       SwingUtilities.invokeLater(() -> {
        Laudo tela ;
        form.abrirFormulario(tela= new Laudo() , jDesktop);
        });
    }//GEN-LAST:event_jmLaudoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SwingUtilities.invokeLater(() -> {
        SPDA tela ;
        form.abrirFormulario(tela= new SPDA() , jDesktop);
        }); 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itens;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu jmCadastramento;
    private javax.swing.JMenuItem jmLaudo;
    private javax.swing.JMenu jmOrcamento;
    private javax.swing.JMenuBar jmbBarraMenu;
    // End of variables declaration//GEN-END:variables
}
